@extends('layouts.app')

@section('title', 'Payroll History')

@section('content')
<div class="mx-6 py-8">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-white flex items-center">
            <i class="fas fa-history mr-3 text-indigo-600"></i> All Payroll History
        </h1>
        <a href="{{ route('payroll.index') }}" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <i class="fas fa-arrow-left mr-2"></i> Back to Payroll Overview
        </a>
    </div>

    <div class="mb-4 flex space-x-2">
        <a href="{{ route('admin.payroll.history.index', ['type' => 'all']) }}" class="px-4 py-2 rounded-md text-sm font-medium {{ request('type', 'all') == 'all' ? 'bg-indigo-600 text-white' : 'bg-gray-200 text-gray-700 hover:bg-gray-300' }}">
            All Payroll History
        </a>
        <a href="{{ route('admin.payroll.history.index', ['type' => 'semiMonthly']) }}" class="px-4 py-2 rounded-md text-sm font-medium {{ request('type') == 'semiMonthly' ? 'bg-indigo-500 text-white' : 'bg-gray-200 text-gray-700 hover:bg-gray-300' }}">
            Semi-Monthly
        </a>
        <a href="{{ route('admin.payroll.history.index', ['type' => 'monthly']) }}" class="px-4 py-2 rounded-md text-sm font-medium {{ request('type') == 'monthly' ? 'bg-indigo-700 text-white' : 'bg-gray-200 text-gray-700 hover:bg-gray-300' }}">
            Monthly
        </a>
    </div>

    <div class="mb-4">
        <input type="text" id="payrollHistorySearch" onkeyup="filterPayrollHistory()" placeholder="Search by date (e.g., Dec 01, 2025)..." class="w-full border-gray-300 rounded-md shadow-sm px-3 py-2 focus:ring-indigo-500 focus:border-indigo-500">
    </div>

    <div class="bg-white rounded-3xl shadow-xl overflow-hidden p-6">
        @if($payPeriods->isEmpty())
            <div class="text-center py-10">
                <p class="text-gray-600 text-lg mb-4">No payroll history available yet.</p>
                <p class="text-gray-600">Generate payrolls to see them listed here.</p>
            </div>
        @else
            <div class="overflow-x-auto">
                <table id="payroll-history-table" class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Pay Period</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Last Regenerated By</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Marked Paid By</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Total Net Pay</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($payPeriods as $period)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-black">{{ \Carbon\Carbon::parse($period->start_date)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($period->end_date)->format('M d, Y') }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-black">{{ ucfirst($period->pay_period_type) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-black">{{ ucfirst($period->status) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-black">{{ $period->generatedBy->name ?? 'N/A' }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-black">{{ $period->regeneratedBy->name ?? 'N/A' }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-black">{{ $period->markedPaidBy->name ?? 'N/A' }}</td>
                                @php
                                    $totalNet = $period->payslips?->sum('net_pay') ?? 0;
                                @endphp
                                <td class="px-6 py-4 whitespace-nowrap font-semibold text-indigo-700">₱{{ number_format($totalNet, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-center">
                                    <a href="{{ route('admin.payroll.history.details', ['payPeriod' => $period->id]) }}" class="text-indigo-600 hover:text-indigo-800 p-1.5 inline-flex items-center justify-center rounded-full hover:bg-gray-200 transition duration-150" title="View Details">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
</div>
@endsection

@push('scripts')
<script>
    function filterPayrollHistory() {
        const searchInput = document.getElementById('payrollHistorySearch').value.toLowerCase();
        const tableBody = document.querySelector('#payroll-history-table tbody');
        const rows = tableBody.querySelectorAll('tr');

        rows.forEach(row => {
            const payPeriodText = row.children[0].textContent.toLowerCase(); // Assuming Pay Period is the first column
            if (payPeriodText.includes(searchInput)) {
                row.classList.remove('hidden');
            } else {
                row.classList.add('hidden');
            }
        });
    }

    document.addEventListener('DOMContentLoaded', function() {
        // You might want to initially filter if there's a search term in the URL or pre-filled input
        filterPayrollHistory();
    });
</script>
@endpush
