@extends('layouts.app')

@section('title', 'Payroll Details')

@section('content')
<div class="container mx-auto px-6 py-8">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-gray-800 flex items-center">
            <i class="fas fa-receipt mr-3 text-indigo-600"></i> Payroll Details for {{ \Carbon\Carbon::parse($payPeriod->start_date)->format('F d, Y') }} - {{ \Carbon\Carbon::parse($payPeriod->end_date)->format('F d, Y') }}
        </h1>
        <a href="{{ route('admin.payroll.history.index') }}" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <i class="fas fa-arrow-left mr-2"></i> Back to Payroll History
        </a>
    </div>

    <div class="bg-white rounded-lg shadow-xl overflow-hidden p-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            <div>
                <p class="text-gray-600 font-semibold">Pay Period Dates:</p>
                <p>{{ \Carbon\Carbon::parse($payPeriod->start_date)->format('F d, Y') }} - {{ \Carbon\Carbon::parse($payPeriod->end_date)->format('F d, Y') }}</p>
            </div>
            <div>
                <p class="text-gray-600 font-semibold">Status:</p>
                <p>{{ ucfirst($payPeriod->status) }}</p>
            </div>
            {{-- Placeholder for generated by, regenerated by, marked paid by --}}
            <div>
                <p class="text-gray-600 font-semibold">Generated By:</p>
                <p>{{ $payPeriod->generatedBy->name ?? 'N/A' }}</p>
            </div>
            <div>
                <p class="text-gray-600 font-semibold">Last Regenerated By:</p>
                <p>{{ $payPeriod->regeneratedBy->name ?? 'N/A' }}</p>
            </div>
            <div>
                <p class="text-gray-600 font-semibold">Marked as Paid By:</p>
                <p>{{ $payPeriod->markedPaidBy->name ?? 'N/A' }}</p>
            </div>
        </div>

        <h2 class="text-xl font-semibold text-gray-700 mb-4 border-b pb-2">Payslips in this Period</h2>

        @if($payPeriod->payslips->isEmpty())
            <p class="text-gray-600">No payslips generated for this pay period.</p>
        @else
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Employee</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Gross Pay</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Deductions</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Net Pay</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($payPeriod->payslips as $payslip)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $payslip->user->name }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">₱{{ number_format($payslip->gross_pay, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">₱{{ number_format($payslip->deductions, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">₱{{ number_format($payslip->net_pay, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-center">
                                    <a href="{{ route('payroll.show-payslip', ['employee' => $payslip->user->id, 'payPeriod' => $payPeriod->id]) }}" class="text-indigo-600 hover:text-indigo-800 p-1.5 inline-flex items-center justify-center rounded-full hover:bg-gray-200 transition duration-150" title="View Payslip">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif

    </div>
</div>
@endsection
