@extends('layouts.app')

@section('title', 'Payroll Details')

@section('content')
<div class="mx-6 py-8">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-white flex items-center">
            <i class="fas fa-receipt mr-3 text-indigo-600"></i> Payroll Details for {{ \Carbon\Carbon::parse($payPeriod->start_date)->format('F d, Y') }} - {{ \Carbon\Carbon::parse($payPeriod->end_date)->format('F d, Y') }}
        </h1>
        <a href="{{ route('admin.payroll.history.index') }}" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <i class="fas fa-arrow-left mr-2"></i> Back to Payroll History
        </a>
    </div>

    <div class="bg-white rounded-3xl shadow-xl overflow-hidden p-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            <div>
                <p class="text-black font-semibold">Pay Period Dates:</p>
                <p class="text-black">{{ \Carbon\Carbon::parse($payPeriod->start_date)->format('F d, Y') }} - {{ \Carbon\Carbon::parse($payPeriod->end_date)->format('F d, Y') }}</p>
            </div>
            <div>
                <p class="text-black font-semibold">Status:</p>
                <p class="text-black">{{ ucfirst($payPeriod->status) }}</p>
            </div>
            {{-- Placeholder for generated by, regenerated by, marked paid by --}}
            <div>
                <p class="text-black font-semibold">Generated By:</p>
                <p class="text-black">{{ $payPeriod->generatedBy->name ?? 'N/A' }}</p>
            </div>
            <div>
                <p class="text-black font-semibold">Last Regenerated By:</p>
                <p class="text-black">{{ $payPeriod->regeneratedBy->name ?? 'N/A' }}</p>
            </div>
            <div>
                <p class="text-black font-semibold">Marked as Paid By:</p>
                <p class="text-black">{{ $payPeriod->markedPaidBy->name ?? 'N/A' }}</p>
            </div>
            @php
                $summaryTotalGrossPay = $payPeriod->payslips->sum('gross_pay');
                $summaryTotalDeductions = $payPeriod->payslips->sum('deductions');
                $summaryTotalNetPay = $payPeriod->payslips->sum('net_pay');
            @endphp
            <div class="md:col-span-2 mt-4 pt-4 border-t border-gray-300">
                <h3 class="text-lg font-bold text-black mb-3">Total Payroll Summary</h3>
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div class="bg-blue-50 p-4 rounded-3xl">
                        <p class="text-sm text-black font-medium mb-1">Total Gross Pay</p>
                        <p class="text-2xl font-bold text-black">₱{{ number_format($summaryTotalGrossPay, 2) }}</p>
                    </div>
                    <div class="bg-red-50 p-4 rounded-3xl">
                        <p class="text-sm text-gray-600 font-medium mb-1">Total Deductions</p>
                        <p class="text-2xl font-bold text-red-600">₱{{ number_format($summaryTotalDeductions, 2) }}</p>
                    </div>
                    <div class="bg-indigo-50 p-4 rounded-3xl">
                        <p class="text-sm text-gray-600 font-medium mb-1">Total Net Pay</p>
                        <p class="text-2xl font-bold text-indigo-700">₱{{ number_format($summaryTotalNetPay, 2) }}</p>
                    </div>
                </div>
            </div>
        </div>

        <h2 class="text-xl font-semibold text-black mb-4 border-b pb-2">Payslips in this Period</h2>

        @if($payPeriod->payslips->isEmpty())
            <p class="text-black">No payslips generated for this pay period.</p>
        @else
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-black uppercase tracking-wider">Employee</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-black uppercase tracking-wider">Gross Pay</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-black uppercase tracking-wider">Deductions</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-black uppercase tracking-wider">Net Pay</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-black uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @php
                            $totalGrossPay = 0;
                            $totalDeductions = 0;
                            $totalNetPay = 0;
                        @endphp
                        @foreach($payPeriod->payslips as $payslip)
                            @php
                                $totalGrossPay += $payslip->gross_pay;
                                $totalDeductions += $payslip->deductions;
                                $totalNetPay += $payslip->net_pay;
                            @endphp
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-center text-black">{{ $payslip->user->name }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-center text-black">₱{{ number_format($payslip->gross_pay, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-center text-black">₱{{ number_format($payslip->deductions, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap text-center text-black">₱{{ number_format($payslip->net_pay, 2) }}</td>
                                <td class="px-6 py-4 whitespace-nowrap flex justify-center items-center">
                                    <a href="{{ route('payroll.show-payslip', ['employee' => $payslip->user->id, 'payPeriod' => $payPeriod->id]) }}" class="text-indigo-600 hover:text-indigo-800 hover:bg-gray-200 transition duration-150" title="View Payslip">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot class="bg-gray-100">
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap font-bold text-center text-gray-900">TOTAL</td>
                            <td class="px-6 py-4 whitespace-nowrap font-bold text-center text-gray-900">₱{{ number_format($totalGrossPay, 2) }}</td>
                            <td class="px-6 py-4 whitespace-nowrap font-bold text-center text-red-600">₱{{ number_format($totalDeductions, 2) }}</td>
                            <td class="px-6 py-4 whitespace-nowrap font-bold text-center text-indigo-700">₱{{ number_format($totalNetPay, 2) }}</td>
                            <td class="px-6 py-4 whitespace-nowrap"></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        @endif

    </div>
</div>
@endsection
